### ISSUE TITLE
BUG: Reference to deprecated pymatgen.analysis.defects

### ISSUE THREAD

**Issue by benrich37** [materialsproject/atomate2#965]
Line 11 of common.schemas.defects.py imports from pymatgen.analysis.defects, which appears to have been deprecated from the latest version of pymatgen (see for [explanation](https://materialsproject.github.io/pymatgen-analysis-defects/intro.html), [lack of defects submodule](https://github.com/materialsproject/pymatgen/tree/master/src/pymatgen/analysis), [existence of outdated import1](https://github.com/materialsproject/atomate2/blob/main/src/atomate2/common/schemas/defects.py), [existence of outdated import2](https://github.com/materialsproject/atomate2/blob/main/src/atomate2/common/jobs/defect.py) )

I do not use this module, but its functionality is tested in the [vasp conftest](https://github.com/materialsproject/atomate2/blob/main/tests/vasp/conftest.py) and thus throws an error when running pytest on the whole repo. This could maybe be an easy fix by adding [the new package](https://materialsproject.github.io/pymatgen-analysis-defects/intro.html) as a dependency and by redirecting old imports (for context I am starting up on helping add a new workflow and am trying to make sure my environment is fully up to snuff before beginning on my test-checks)

**Comment by benrich37** [comment]
Thank you! I'm okay with its existence knowing that it's not just a problem on my end. I'm having trouble installing with strict to fix this issue (pip install -e '.[strict]' gives the error code pasted below) but that is a separate issue that is likely an issue on my end for a reason I don't understand yet (installing with either tests or dev seems to uninstall fireworks, phonopy, ase, torch, and abipy so my environment has those installed manually through pip at the moment)

ERROR: Could not find a version that satisfies the requirement quippy-ase==0.9.14; extra == "strict" (from atomate2[strict]) (from versions: none)
ERROR: No matching distribution found for quippy-ase==0.9.14; extra == "strict"

**Comment by esoteric-ephemera** [comment]
The import in `conftest` (now `utils.testing.vasp`) was fixed in [#1159](https://github.com/materialsproject/atomate2/pull/1159). Not sure why the quippy install wasn't working, but perhaps an issue with using python>=3.12?

Closing for now, feel free to reopen if I missed something

Just to note: the add-on package `pymatgen-analysis-defects` isn't deprecated. The original module which is no longer available in `pymatgen`, is deprecated.

**Comment by thomasloux** [comment]
Hey @esoteric-ephemera, this is issue still persists in the current code.
After git cloning and running `uv sync --extra dev --extra tests --extra phonons`
Some tests still fail because of pymatgen defects: `uv run pytest . --ignore=tests/ase --ignore=tests/abinit``

```
ERROR tests/aims - ModuleNotFoundError: No module named 'pymatgen.io.aims'
ERROR tests/common/schemas/test_defect.py
ERROR tests/forcefields - ModuleNotFoundError: No module named 'torch'
ERROR tests/openff_md - ModuleNotFoundError: No module named 'openff'
ERROR tests/openmm_md - ModuleNotFoundError: No module named 'openmm'
ERROR tests/vasp/flows/test_approx_neb.py
ERROR tests/vasp/flows/test_defect.py
ERROR tests/vasp/schemas/test_defect.py
```
tests/vasp/flows/test_defect.py, tests/vasp/schemas/test_defect.py and tests/common/schemas/test_defect.py are directly caused by ModuleNotFoundError: No module named 'pymatgen.analysis.defects'.

Should these workflows be deprecated as well? I don't really understand the status on defects workflow.

**Comment by JaGeo** [comment]
@thomasloux maybe take a look into how we run the workflows here. Usually, we use "strict" for indtallation in this case.

And, no, this should not be deprecated. There is a defect addon to pymatgen that we install.
